title: "Rettangoli Test Suite"
sections:
  - title: "View"
    files: "viz/specs/view"
  - title: "Text"
    files: "viz/specs/text"
  - title: "Button"
    files: "viz/specs/button"
  - title: "Image"
    files: "viz/specs/image"
  - title: "Svg"
    files: "viz/specs/svg"
  - title: "Input"
    files: "viz/specs/input"
  - title: "Textarea"
    files: "viz/specs/textarea"
  - title: "Select"
    files: "viz/specs/select"
  - title: "Popover"
    files: "viz/specs/popover"
  - title: "Sidebar"
    files: "viz/specs/sidebar"
  - title: "Page-Outline"
    files: "viz/specs/page-outline"
  - title: "Navbar"
    files: "viz/specs/navbar"
  - title: "Form"
    files: "viz/specs/form"
  - title: "Dialog"
    files: "viz/specs/dialog"