- html lang="en":
    - head:
        - $partial: seo1
          page: ${page}
          seo: ${seo}
          title: ${title}
        - link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@rettangoli/ui@1.0.0-rc7/dist/themes/base.css" onerror="this.onerror=null;this.href='/public/base.css'":
        - link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@rettangoli/ui@1.0.0-rc7/dist/themes/theme-rtgl-slate.css" onerror="this.onerror=null;this.href='/public/theme-rtgl-slate.css'":
        - script src="https://cdn.jsdelivr.net/npm/construct-style-sheets-polyfill@3.1.0/dist/adoptedStyleSheets.min.js":
        - script src="https://cdn.jsdelivr.net/npm/@rettangoli/ui@1.0.0-rc7/dist/rettangoli-iife-ui.min.js" onerror="this.onerror=null;this.src='/public/rettangoli-iife-ui.min.js'":
        - script src="/public/rtgl-icons.js":

    - body.dark:
        - rtgl-view:
            - rtgl-view pos="abs" edge="t" ah="c" bgc="bg":
                - $partial: navbar1
                  title: ${site.navbar.title}
                  cta: ${site.navbar.cta}
            - rtgl-view w=f:
                - rtgl-view h="48":
                - rtgl-view w="f" ah="c":
                    - rtgl-view w=f ph="lg" pb="lg" ah=c:
                        - "${content}"
