imports:
  templates:
    base: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/templates/base.yaml
    docs: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/templates/docs.yaml
    landing-features: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/templates/landing-features.yaml
    blog-article-list: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/templates/blog-article-list.yaml
    blog-article: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/templates/blog-article.yaml
  partials:
    seo: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/partials/seo.yaml
    navbar: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/partials/navbar.yaml
    mobile-nav: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/partials/mobile-nav.yaml
    docs-sidebar: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/partials/docs-sidebar.yaml
    top-navbar: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/partials/top-navbar.yaml
    footer: https://cdn.jsdelivr.net/npm/@rettangoli/sitekit@1.0.3/sitekit/partials/footer.yaml

markdownit:
  html: true
  linkify: true
  typographer: false
  shiki:
    enabled: true
    theme: slack-dark
  codePreview:
    enabled: true
    showSource: true
    theme: slack-dark
  headingAnchors:
    enabled: true
    slugMode: ascii
    wrap: true
    fallback: section
build:
  keepMarkdownFiles: true
