name: Publish rettangoli-ui to npm
on:
  push:
    tags:
      - 'ui-v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2

      # Install dependencies from root
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build UI Package
        run: bun run build
        working-directory: ./packages/rettangoli-ui

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Publish to npm
      - name: Publish rettangoli-ui to npm
        run: npm publish
        working-directory: ./packages/rettangoli-ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}